In [1]:
import scipy.io

# Load the depth data from the .mat file
mat_data = scipy.io.loadmat(r"C:\Users\ayyag\OneDrive\Desktop\UTD - MHAD\Depth\Depth\a1_s1_t1_depth.mat")

# Access the depth data array
depth_data = mat_data['d_depth']


In [2]:
import scipy.io
import os

# Directory containing the .mat files
directory = r'C:\Users\ayyag\OneDrive\Desktop\UTD - MHAD\Depth\Depth'

# Iterate over each file in the directory
for filename in os.listdir(directory):
    if filename.endswith('.mat'):
        # Load the .mat file
        file_path = os.path.join(directory, filename)
        mat_data = scipy.io.loadmat(file_path)

        # Extract the depth data from the loaded file
        depth_data = mat_data['d_depth']
        
        # Process the depth data as needed
        # ...

        # Print information or perform operations on the depth data
        print(f"Depth data from file: {filename}")
        print("Shape:", depth_data.shape)
        # ...

        # Continue processing other files or perform additional operations


Depth data from file: a10_s1_t1_depth.mat
Shape: (240, 320, 76)
Depth data from file: a10_s1_t2_depth.mat
Shape: (240, 320, 73)
Depth data from file: a10_s1_t3_depth.mat
Shape: (240, 320, 74)
Depth data from file: a10_s1_t4_depth.mat
Shape: (240, 320, 73)
Depth data from file: a10_s2_t1_depth.mat
Shape: (240, 320, 67)
Depth data from file: a10_s2_t2_depth.mat
Shape: (240, 320, 68)
Depth data from file: a10_s2_t3_depth.mat
Shape: (240, 320, 64)
Depth data from file: a10_s2_t4_depth.mat
Shape: (240, 320, 67)
Depth data from file: a10_s3_t1_depth.mat
Shape: (240, 320, 80)
Depth data from file: a10_s3_t2_depth.mat
Shape: (240, 320, 80)
Depth data from file: a10_s3_t3_depth.mat
Shape: (240, 320, 83)
Depth data from file: a10_s3_t4_depth.mat
Shape: (240, 320, 82)
Depth data from file: a10_s4_t1_depth.mat
Shape: (240, 320, 67)
Depth data from file: a10_s4_t2_depth.mat
Shape: (240, 320, 65)
Depth data from file: a10_s4_t3_depth.mat
Shape: (240, 320, 67)
Depth data from file: a10_s4_t4_depth.ma

Depth data from file: a14_s1_t3_depth.mat
Shape: (240, 320, 82)
Depth data from file: a14_s1_t4_depth.mat
Shape: (240, 320, 80)
Depth data from file: a14_s2_t1_depth.mat
Shape: (240, 320, 73)
Depth data from file: a14_s2_t2_depth.mat
Shape: (240, 320, 75)
Depth data from file: a14_s2_t3_depth.mat
Shape: (240, 320, 78)
Depth data from file: a14_s2_t4_depth.mat
Shape: (240, 320, 73)
Depth data from file: a14_s3_t1_depth.mat
Shape: (240, 320, 63)
Depth data from file: a14_s3_t2_depth.mat
Shape: (240, 320, 66)
Depth data from file: a14_s3_t3_depth.mat
Shape: (240, 320, 72)
Depth data from file: a14_s3_t4_depth.mat
Shape: (240, 320, 69)
Depth data from file: a14_s4_t1_depth.mat
Shape: (240, 320, 81)
Depth data from file: a14_s4_t2_depth.mat
Shape: (240, 320, 71)
Depth data from file: a14_s4_t3_depth.mat
Shape: (240, 320, 76)
Depth data from file: a14_s4_t4_depth.mat
Shape: (240, 320, 65)
Depth data from file: a14_s5_t1_depth.mat
Shape: (240, 320, 73)
Depth data from file: a14_s5_t2_depth.ma

Depth data from file: a18_s2_t3_depth.mat
Shape: (240, 320, 49)
Depth data from file: a18_s2_t4_depth.mat
Shape: (240, 320, 52)
Depth data from file: a18_s3_t1_depth.mat
Shape: (240, 320, 53)
Depth data from file: a18_s3_t2_depth.mat
Shape: (240, 320, 52)
Depth data from file: a18_s3_t3_depth.mat
Shape: (240, 320, 57)
Depth data from file: a18_s3_t4_depth.mat
Shape: (240, 320, 57)
Depth data from file: a18_s4_t1_depth.mat
Shape: (240, 320, 54)
Depth data from file: a18_s4_t2_depth.mat
Shape: (240, 320, 52)
Depth data from file: a18_s4_t3_depth.mat
Shape: (240, 320, 60)
Depth data from file: a18_s4_t4_depth.mat
Shape: (240, 320, 55)
Depth data from file: a18_s5_t1_depth.mat
Shape: (240, 320, 65)
Depth data from file: a18_s5_t2_depth.mat
Shape: (240, 320, 49)
Depth data from file: a18_s5_t3_depth.mat
Shape: (240, 320, 50)
Depth data from file: a18_s5_t4_depth.mat
Shape: (240, 320, 48)
Depth data from file: a18_s6_t1_depth.mat
Shape: (240, 320, 75)
Depth data from file: a18_s6_t2_depth.ma

Depth data from file: a21_s2_t4_depth.mat
Shape: (240, 320, 70)
Depth data from file: a21_s3_t1_depth.mat
Shape: (240, 320, 70)
Depth data from file: a21_s3_t2_depth.mat
Shape: (240, 320, 73)
Depth data from file: a21_s3_t3_depth.mat
Shape: (240, 320, 68)
Depth data from file: a21_s3_t4_depth.mat
Shape: (240, 320, 80)
Depth data from file: a21_s4_t1_depth.mat
Shape: (240, 320, 73)
Depth data from file: a21_s4_t2_depth.mat
Shape: (240, 320, 77)
Depth data from file: a21_s4_t3_depth.mat
Shape: (240, 320, 78)
Depth data from file: a21_s4_t4_depth.mat
Shape: (240, 320, 77)
Depth data from file: a21_s5_t1_depth.mat
Shape: (240, 320, 85)
Depth data from file: a21_s5_t2_depth.mat
Shape: (240, 320, 77)
Depth data from file: a21_s5_t3_depth.mat
Shape: (240, 320, 82)
Depth data from file: a21_s5_t4_depth.mat
Shape: (240, 320, 75)
Depth data from file: a21_s6_t1_depth.mat
Shape: (240, 320, 107)
Depth data from file: a21_s6_t2_depth.mat
Shape: (240, 320, 97)
Depth data from file: a21_s6_t3_depth.m

Depth data from file: a25_s3_t4_depth.mat
Shape: (240, 320, 61)
Depth data from file: a25_s4_t1_depth.mat
Shape: (240, 320, 69)
Depth data from file: a25_s4_t2_depth.mat
Shape: (240, 320, 68)
Depth data from file: a25_s4_t3_depth.mat
Shape: (240, 320, 59)
Depth data from file: a25_s4_t4_depth.mat
Shape: (240, 320, 57)
Depth data from file: a25_s5_t1_depth.mat
Shape: (240, 320, 51)
Depth data from file: a25_s5_t2_depth.mat
Shape: (240, 320, 58)
Depth data from file: a25_s5_t3_depth.mat
Shape: (240, 320, 49)
Depth data from file: a25_s5_t4_depth.mat
Shape: (240, 320, 50)
Depth data from file: a25_s6_t1_depth.mat
Shape: (240, 320, 59)
Depth data from file: a25_s6_t2_depth.mat
Shape: (240, 320, 57)
Depth data from file: a25_s6_t3_depth.mat
Shape: (240, 320, 49)
Depth data from file: a25_s6_t4_depth.mat
Shape: (240, 320, 70)
Depth data from file: a25_s7_t1_depth.mat
Shape: (240, 320, 51)
Depth data from file: a25_s7_t2_depth.mat
Shape: (240, 320, 58)
Depth data from file: a25_s7_t3_depth.ma

Depth data from file: a3_s4_t2_depth.mat
Shape: (240, 320, 62)
Depth data from file: a3_s4_t3_depth.mat
Shape: (240, 320, 66)
Depth data from file: a3_s4_t4_depth.mat
Shape: (240, 320, 57)
Depth data from file: a3_s5_t1_depth.mat
Shape: (240, 320, 61)
Depth data from file: a3_s5_t2_depth.mat
Shape: (240, 320, 79)
Depth data from file: a3_s5_t3_depth.mat
Shape: (240, 320, 72)
Depth data from file: a3_s5_t4_depth.mat
Shape: (240, 320, 74)
Depth data from file: a3_s6_t1_depth.mat
Shape: (240, 320, 80)
Depth data from file: a3_s6_t2_depth.mat
Shape: (240, 320, 75)
Depth data from file: a3_s6_t3_depth.mat
Shape: (240, 320, 81)
Depth data from file: a3_s6_t4_depth.mat
Shape: (240, 320, 70)
Depth data from file: a3_s7_t1_depth.mat
Shape: (240, 320, 50)
Depth data from file: a3_s7_t2_depth.mat
Shape: (240, 320, 60)
Depth data from file: a3_s7_t3_depth.mat
Shape: (240, 320, 49)
Depth data from file: a3_s7_t4_depth.mat
Shape: (240, 320, 64)
Depth data from file: a3_s8_t1_depth.mat
Shape: (240, 3

Depth data from file: a7_s5_t2_depth.mat
Shape: (240, 320, 63)
Depth data from file: a7_s5_t3_depth.mat
Shape: (240, 320, 69)
Depth data from file: a7_s5_t4_depth.mat
Shape: (240, 320, 71)
Depth data from file: a7_s6_t1_depth.mat
Shape: (240, 320, 62)
Depth data from file: a7_s6_t2_depth.mat
Shape: (240, 320, 64)
Depth data from file: a7_s6_t3_depth.mat
Shape: (240, 320, 60)
Depth data from file: a7_s6_t4_depth.mat
Shape: (240, 320, 56)
Depth data from file: a7_s7_t1_depth.mat
Shape: (240, 320, 67)
Depth data from file: a7_s7_t2_depth.mat
Shape: (240, 320, 74)
Depth data from file: a7_s7_t3_depth.mat
Shape: (240, 320, 81)
Depth data from file: a7_s7_t4_depth.mat
Shape: (240, 320, 71)
Depth data from file: a7_s8_t1_depth.mat
Shape: (240, 320, 65)
Depth data from file: a7_s8_t2_depth.mat
Shape: (240, 320, 62)
Depth data from file: a7_s8_t3_depth.mat
Shape: (240, 320, 55)
Depth data from file: a7_s8_t4_depth.mat
Shape: (240, 320, 57)
Depth data from file: a8_s1_t1_depth.mat
Shape: (240, 3

In [3]:
import numpy as np

# Print the dimensions of the depth data
print("Depth data shape:", depth_data.shape)

# Access a specific frame of the depth data
frame_index = 0
frame = depth_data[frame_index]

# Perform further operations on the frame as needed
print("Shape of the frame:", frame.shape)


Depth data shape: (240, 320, 66)
Shape of the frame: (320, 66)


In [4]:
import numpy as np
import matplotlib.pyplot as plt

# Access a specific frame of the depth data
frame_index = 0
frame = depth_data[frame_index]

# Display the depth frame as an image
plt.imshow(frame, cmap='gray')
plt.colorbar()
plt.title('Depth Frame')
plt.show()


In [8]:
print(mat_data['d_depth'])

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# Create a figure and axis for the animation
fig, ax = plt.subplots()

# Function to update the plot for each frame
def update(frame_index):
    # Clear the current plot
    ax.cla()

    # Access the current frame of the depth data
    frame = depth_data[frame_index]

    # Display the depth frame as an image
    ax.imshow(frame.T, cmap='gray')  # Transpose the frame

    # Set appropriate labels if needed
    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_title(f'Frame {frame_index+1}')

# Animate the frames and assign to a variable
animation = FuncAnimation(fig, update, frames=len(depth_data), interval=100)

# Display the animation
plt.show()


In [ ]:
import numpy as np
import scipy.io
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Step 1: Load the Depth Data
depth_data = scipy.io.loadmat('path_to_depth_data.mat')['depth']
labels = np.load('path_to_labels.npy')

# Step 2: Resize and Normalize
resized_depth_data = []  # Store resized depth frames
scaler = MinMaxScaler(feature_range=(0, 1))  # Scaler for normalization

desired_width = 128  # Set desired width for resizing
desired_height = 128  # Set desired height for resizing

for frame in depth_data:
    # Resize the depth frame to desired dimensions
    resized_frame = cv2.resize(frame, (desired_width, desired_height))
    
    # Normalize the resized frame
    normalized_frame = scaler.fit_transform(resized_frame)
    
    resized_depth_data.append(normalized_frame)

resized_depth_data = np.array(resized_depth_data)

# Step 3: Temporal Alignment (if applicable)
# ...

# Step 4: Data Augmentation (if applicable)
# ...

# Step 5: Splitting the Dataset
X_train, X_val, y_train, y_val = train_test_split(resized_depth_data, labels, test_size=0.2, stratify=labels)
X_val, X_test, y_val, y_test = train_test_split(X_val, y_val, test_size=0.5, stratify=y_val)

# Step 6: Optional - Further Processing
# ...

# Print the shapes of the pre-processed datasets
print("Training set shape:", X_train.shape)
print("Validation set shape:", X_val.shape)
print("Testing set shape:", X_test.shape)
